## EEP 153 Team Lind Project 2

### Mediterranean Diets and the Minimum-Cost Diets

The following code helps us visualize what constitutes a minimum-cost mediterranean diet looks like. This will help build our basis to answer our main question: is a mediterranean diet attainable given regional variability, namely in Californiaâ€” looking at Berkeley, a relatively well-off community and a CalEnviroScreen disadvantaged community in Fresno.

We will first begin by installing the modules given to us in lecture.

In [1]:
!pip install -r requirements.txt

Requirement already satisfied: numpy>=1.20.3 in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.21.5)
Requirement already satisfied: pandas>=1.2.5 in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.3.5)
Requirement already satisfied: pint>=0.18 in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (0.18)
Requirement already satisfied: requests>=2.26.0 in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (2.26.0)
Requirement already satisfied: eep153_tools in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (0.11)
Requirement already satisfied: gnupg in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 17)) (2.3.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.9/site-packages (from pandas>=1.2.5->-r requirements.txt (line 7)) (2.8.0)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.9/site-packages (from pandas>=1.2.5->-r requirements.txt (line 7)) (2021.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.9/site-packages (from pint>=0.18->-r requirements.txt (line 10)) (21.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 13)) (2019.11.28)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 13)) (1.25.7)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 13)) (2.0.0)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 13)) (2.8)
Requirement already satisfied: psutil>=1.2.1 in /opt/conda/lib/python3.9/site-packages (from gnupg->-r requirements.txt (line 17)) (5.9.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=1.2.5->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.9/site-packages (from packaging->pint>=0.18->-r requirements.txt (line 10)) (3.0.7)

Now we can assign our API key from the USDA Food Central DataBase that we will use to assign food items with an FDC ID and according nutritional information.

In [2]:
apikey = "mcahDx8n8FkXewC5PNO9wlSX64zLwktGoSChuixa" #API Key for Project Group James Lind

In [3]:
#Load in the USDA Food Central DataBase and other necessary packages
import fooddatacentral as fdc
import pandas as pd

After researching the mediterranean diet, we came up with a grocery list we would apply to our populations of interest. Our food items include: olive oil, chickpeas, eggs, canned tuna, milk, feta, greek yogurt, oranges, avocado, broccoli, spinach, sweet potato, rice, and bread.

Now we can assign our all of our food items their corresponding FDC ID number that will provide us the necessary information to understand their nutrients.

In [4]:
id1 = 1582039 #Olive oil 
id2 = 1100433 #Chickpeas
id3 = 747997 #Eggs
id4 = 334194 #Canned tuna
id5 = 1904187 #Milk
id6 = 173420 #Feta
id7 = 170903 #Greek yogurt
id8 = 1102597 #Oranges
id9 = 1102652 # Avocado
id10 = 1103278 #Tomato
id11 = 1103177 #Broccoli
id12 = 1103136 #Spinach
id13 = 1103249 #Sweet potato
id14 = 2077766 #Rice
id15 = 1100740 #Bread

Now that we have assgined our food items with their FDC ID, we will organize the called information before creating a dataframe. This entails dropping repetitive columns.

In [5]:
#Calling each food item into a data frame and dropping the units column
oliveoil = fdc.nutrients(apikey, fdc_id = id1).drop(["Units"], axis = 1)

chickpea = fdc.nutrients(apikey, fdc_id = id2).drop(["Units"], axis = 1)

egg = fdc.nutrients(apikey, fdc_id = id3).drop(["Units"], axis = 1)

tuna = fdc.nutrients(apikey,fdc_id = id4).drop(["Units"], axis = 1)

milk = fdc.nutrients(apikey,fdc_id = id5).drop(["Units"], axis = 1)

feta = fdc.nutrients(apikey,fdc_id = id6).drop(["Units"], axis = 1)

yogurt = fdc.nutrients(apikey,fdc_id=id7).drop(["Units"], axis=1)

orange = fdc.nutrients(apikey,fdc_id=id8).drop(["Units"], axis=1)

avocado = fdc.nutrients(apikey,fdc_id=id9).drop(["Units"], axis=1)

tomato = fdc.nutrients(apikey,fdc_id=id10).drop(["Units"], axis=1)

broccoli = fdc.nutrients(apikey,fdc_id=id11).drop(["Units"], axis=1)

spinach = fdc.nutrients(apikey,fdc_id=id12).drop(["Units"], axis=1)

potato = fdc.nutrients(apikey,fdc_id=id13).drop(["Units"], axis=1)

rice = fdc.nutrients(apikey,fdc_id=id14).drop(["Units"], axis=1)

bread = fdc.nutrients(apikey,fdc_id=id15).drop(["Units"], axis=1)

#Renaming of Columns into the actual food items
units = fdc.nutrients(apikey,fdc_id = id3).drop(["Quantity"], axis = 1)

oliveoil.rename(columns = {'Quantity':'Olive oil'}, inplace = True)

chickpea.rename(columns = {'Quantity':'Chickpeas'}, inplace = True)

egg.rename(columns = {'Quantity':'Eggs'}, inplace = True)

tuna.rename(columns = {'Quantity':'Canned tuna'}, inplace = True)

milk.rename(columns = {'Quantity':'Milk'}, inplace = True)

feta.rename(columns = {'Quantity':'Feta'}, inplace = True)

yogurt.rename(columns = {'Quantity':'Greek yogurt'}, inplace = True)

orange.rename(columns = {'Quantity':'Oranges'}, inplace = True)

avocado.rename(columns = {'Quantity':'Avocado'}, inplace = True)

tomato.rename(columns = {'Quantity':'Tomato'}, inplace = True)

broccoli.rename(columns = {'Quantity':'Broccoli'}, inplace = True)

spinach.rename(columns = {'Quantity':'Spinach'}, inplace = True)

potato.rename(columns = {'Quantity':'Sweet potatoes'}, inplace = True)

rice.rename(columns = {'Quantity':'Rice'}, inplace = True)

bread.rename(columns = {'Quantity':'Whole Wheat Bread'}, inplace = True)

We will now create a matrix *A* with A min and A max array to correst to diet inequalities.

In [6]:
#Need to convert NaN into 0s via professors lecture code
df = pd.concat([units, oliveoil,chickpea, egg, tuna, milk, feta, yogurt, orange, avocado, 
                tomato, broccoli, spinach, potato, rice, bread], axis = 1)

FoodNutrients= df.fillna(0)

FoodNutrients

,Units,Olive oil,Chickpeas,Eggs,Canned tuna,Milk,Feta,Greek yogurt,Oranges,Avocado,Tomato,Broccoli,Spinach,Sweet potatoes,Rice,Whole Wheat Bread
Proximates,g,0.0,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Water,g,0.0,64.03,86.30,79.00,0.00,55.220,83.560,86.75,73.23,89.79,85.88,91.40,76.03,0.00,38.7
Energy,kJ,800.0,146.00,231.00,376.00,62.00,1107.000,305.000,47.00,160.00,50.00,61.00,23.00,114.00,356.00,254.0
Nitrogen,g,0.0,0.00,1.71,3.04,0.00,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Protein,g,0.0,8.19,10.70,19.00,3.33,14.210,9.950,0.94,2.00,1.08,2.84,2.86,1.30,6.67,12.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cystine,0,0.0,0.00,0.00,0.00,0.00,0.083,0.048,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Starch,0,0.0,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
MUFA 14:1,0,0.0,0.00,0.00,0.00,0.00,0.000,0.021,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
PUFA 18:3i,0,0.0,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
PUFA 20:3,0,0.0,0.00,0.00,0.00,0.00,0.000,0.002,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0

### Deliverable [A] Dietary Reference Intakes

#### Function that takes arguments of characteristics of person (age, sex, weight, etc.) and  return a pandas.Series of Dietary Reference Intakes (DRIs) or Recommended Daily Allowances RDA 

Now we can begin writing the function for Deliverable A. We start by defining the min and max nutritional requirements by importing the csv files.

In [7]:
def person(age, sex):
    bmin = pd.read_csv('./diet_minimums.csv').set_index('Nutrition').iloc[:,2:]
    bmax = pd.read_csv('./diet_maximums.csv').set_index('Nutrition').iloc[:,2:]
    return

In [8]:
bmin = pd.read_csv('./diet_minimums.csv').set_index('Nutrition').iloc[:,2:]

bmax = pd.read_csv('./diet_maximums.csv').set_index('Nutrition').iloc[:,2:]

bmin #prints table for min nutritional requirements for ages and gender

,C 1-3,F 4-8,M 4-8,F 9-13,M 9-13,F 14-18,M 14-18,F 19-30,M 19-30,F 31-50,M 31-50,F 51+,M 51+
Nutrition,,,,,,,,,,,,,
Energy,1000.0,1200.0,1400.0,1600.0,1800.0,1800.0,2200.0,2000.0,2400.0,1800.0,2200.0,1600.0,2000.0
Protein,13.0,19.0,19.0,34.0,34.0,46.0,52.0,46.0,56.0,46.0,56.0,46.0,56.0
"Fiber, total dietary",14.0,16.8,19.6,22.4,25.2,25.2,30.8,28.0,33.6,25.2,30.8,22.4,28.0
"Folate, DFE",150.0,200.0,200.0,300.0,300.0,400.0,400.0,400.0,400.0,400.0,400.0,400.0,400.0
"Calcium, Ca",700.0,1000.0,1000.0,1300.0,1300.0,1300.0,1300.0,1000.0,1000.0,1000.0,1000.0,1200.0,1000.0
"Carbohydrate, by difference",130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0
"Iron, Fe",7.0,10.0,10.0,8.0,8.0,15.0,11.0,18.0,8.0,18.0,8.0,8.0,8.0
"Magnesium, Mg",80.0,130.0,130.0,240.0,240.0,360.0,410.0,310.0,400.0,320.0,420.0,320.0,420.0
Niacin,6.0,8.0,8.0,12.0,12.0,14.0,16.0,14.0,16.0,14.0,16.0,14.0,16.0
"Phosphorus, P",460.0,500.0,500.0,1250.0,1250.0,1250.0,1250.0,700.0,700.0,700.0,700.0,700.0,700.0
"Potassium, K",3000.0,3800.0,3800.0,4500.0,4500.0,4700.0,4700.0,4700.0,4700.0,4700.0,4700.0,4700.0,4700.0
Riboflavin,0.5,0.6,0.6,0.9,0.9,1.0,1.3,1.1,1.3,1.1,1.3,1.1,1.3
Thiamin,0.5,0.6,0.6,0.9,0.9,1.0,1.2,1.1,1.2,1.1,1.2,1.1,1.2
"Vitamin A, RAE",300.0,400.0,400.0,600.0,600.0,700.0,900.0,700.0,900.0,700.0,900.0,700.0,900.0
Vitamin B-12,0.9,1.2,1.2,1.8,1.8,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4
Vitamin B-6,0.5,0.6,0.6,1.0,1.0,1.2,1.3,1.3,1.3,1.3,1.3,1.5,1.7
"Vitamin C, total ascorbic acid",15.0,25.0,25.0,45.0,45.0,65.0,75.0,75.0,90.0,75.0,90.0,75.0,90.0
Vitamin E (alpha-tocopherol),6.0,7.0,7.0,11.0,11.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0
Vitamin K (phylloquinone),30.0,55.0,55.0,60.0,60.0,75.0,75.0,90.0,120.0,90.0,120.0,90.0,120.0
"Zinc, Zn",3.0,5.0,5.0,8.0,8.0,9.0,11.0,8.0,11.0,8.0,11.0,8.0,11.0

In [9]:
bmax #prints max requirement for Sodium

,C 1-3,F 4-8,M 4-8,F 9-13,M 9-13,F 14-18,M 14-18,F 19-30,M 19-30,F 31-50,M 31-50,F 51+,M 51+
Nutrition,,,,,,,,,,,,,
"Sodium, Na",1500,1900,1900,2200,2200,2300,2300,2300,2300,2300,2300,2300,2300

Next, we will pull individual minimum nutrient strings from data frame for genders and ages and assigns them to dri variables.

In [10]:
def dri_female_min(age):
    if age in range(1,4):
        return bmin.iloc[:, 0]
    if age in range(4,9):
        return bmin.iloc[:, 1]
    if age in range(9,14):
        return bmin.iloc[:, 3]
    if age in range(14,19):
        return bmin.iloc[:, 5]
    if age in range(19,31): 
        return bmin.iloc[:, 7]
    if age in range(31,51):
        return bmin.iloc[:, 9]
    if age >= 51:
        return bmin.iloc[:, 11]
    
def dri_male_min(age):
    if age in range(1,4):
        return bmin.iloc[:, 0]
    if age in range(4,9):
        return bmin.iloc[:, 2]
    if age in range(9,14):
        return bmin.iloc[:, 4]
    if age in range(14,19):
        return bmin.iloc[:, 6]
    if age in range(19,31): 
        return bmin.iloc[:, 8]
    if age in range(31,51):
        return bmin.iloc[:, 10]
    if age >= 51:
        return bmin.iloc[:, 12]
    
def get_dri_min(age, sex):
    if sex == "M":
        return dri_male_min(age)
    else:
        return dri_female_min(age)
get_dri_min(5, 'M')

Nutrition
Energy                            1400.0
Protein                             19.0
Fiber, total dietary                19.6
Folate, DFE                        200.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            10.0
Magnesium, Mg                      130.0
Niacin                               8.0
Phosphorus, P                      500.0
Potassium, K                      3800.0
Riboflavin                           0.6
Thiamin                              0.6
Vitamin A, RAE                     400.0
Vitamin B-12                         1.2
Vitamin B-6                          0.6
Vitamin C, total ascorbic acid      25.0
Vitamin E (alpha-tocopherol)         7.0
Vitamin K (phylloquinone)           55.0
Zinc, Zn                             5.0
Name: M 4-8, dtype: float64

Now we can pull the nutritional requirements based on different ages and sexes. Here we are checking the nutritional requirements for a 22 year old female and a 22 year old male.

In [11]:
get_dri_min(22, 'F')

Nutrition
Energy                            2000.0
Protein                             46.0
Fiber, total dietary                28.0
Folate, DFE                        400.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            18.0
Magnesium, Mg                      310.0
Niacin                              14.0
Phosphorus, P                      700.0
Potassium, K                      4700.0
Riboflavin                           1.1
Thiamin                              1.1
Vitamin A, RAE                     700.0
Vitamin B-12                         2.4
Vitamin B-6                          1.3
Vitamin C, total ascorbic acid      75.0
Vitamin E (alpha-tocopherol)        15.0
Vitamin K (phylloquinone)           90.0
Zinc, Zn                             8.0
Name: F 19-30, dtype: float64

In [12]:
get_dri_min(22, 'M')

Nutrition
Energy                            2400.0
Protein                             56.0
Fiber, total dietary                33.6
Folate, DFE                        400.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                             8.0
Magnesium, Mg                      400.0
Niacin                              16.0
Phosphorus, P                      700.0
Potassium, K                      4700.0
Riboflavin                           1.3
Thiamin                              1.2
Vitamin A, RAE                     900.0
Vitamin B-12                         2.4
Vitamin B-6                          1.3
Vitamin C, total ascorbic acid      90.0
Vitamin E (alpha-tocopherol)        15.0
Vitamin K (phylloquinone)          120.0
Zinc, Zn                            11.0
Name: M 19-30, dtype: float64

We are checking the nutritional requirements for a 30 year old female and a 30 year old male.

In [13]:
get_dri_min(30, 'F')

Nutrition
Energy                            2000.0
Protein                             46.0
Fiber, total dietary                28.0
Folate, DFE                        400.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            18.0
Magnesium, Mg                      310.0
Niacin                              14.0
Phosphorus, P                      700.0
Potassium, K                      4700.0
Riboflavin                           1.1
Thiamin                              1.1
Vitamin A, RAE                     700.0
Vitamin B-12                         2.4
Vitamin B-6                          1.3
Vitamin C, total ascorbic acid      75.0
Vitamin E (alpha-tocopherol)        15.0
Vitamin K (phylloquinone)           90.0
Zinc, Zn                             8.0
Name: F 19-30, dtype: float64

In [14]:
get_dri_min(30, 'M')

Nutrition
Energy                            2400.0
Protein                             56.0
Fiber, total dietary                33.6
Folate, DFE                        400.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                             8.0
Magnesium, Mg                      400.0
Niacin                              16.0
Phosphorus, P                      700.0
Potassium, K                      4700.0
Riboflavin                           1.3
Thiamin                              1.2
Vitamin A, RAE                     900.0
Vitamin B-12                         2.4
Vitamin B-6                          1.3
Vitamin C, total ascorbic acid      90.0
Vitamin E (alpha-tocopherol)        15.0
Vitamin K (phylloquinone)          120.0
Zinc, Zn                            11.0
Name: M 19-30, dtype: float64

Next, we define a function that grabs individual maximum strings and assigns them to the dri_male(female)_max variable.

In [15]:
def dri_female_max(age): 
    if age in range(1,4):
        return bmax.iloc[:, 0]
    if age in range(4,9):
        return bmax.iloc[:, 1]
    if age in range(9,14):
        return bmax.iloc[:, 3]
    if age in range(14,19):
        return bmax.iloc[:, 5]
    if age in range(19,31): 
        return bmax.iloc[:, 7]
    if age in range(31,51):
        return bmax.iloc[:, 9]
    if age >= 51:
        return bmax.iloc[:, 11]
    
def dri_male_max(age):
    if age in range(1,4):
        return bmax.iloc[:, 0]
    if age in range(4,9):
        return bmax.iloc[:, 2]
    if age in range(9,14):
        return bmax.iloc[:, 4]
    if age in range(14,19):
        return bmax.iloc[:, 6]
    if age in range(19,31): 
        return bmax.iloc[:, 8]
    if age in range(31,51):
        return bmax.iloc[:, 10]
    if age >= 51:
        return bmax.iloc[:, 12]
def get_dri_max(age, sex):
    if sex == "M":
        return dri_male_max(age)
    else:
        return dri_female_max(age)

We will check the function for a 22 year old male.

In [16]:
get_dri_max(22, 'M')

Nutrition
Sodium, Na    2300
Name: M 19-30, dtype: int64

### Deliverable [A] Data on prices for different foods

#### Construct a google spreadsheet of different prices of different foods.

Before we begin importing our spreadsheet, we are first checking that the nutrients for our food items the FCD ID is working.

In [17]:
id = id1 #Checking nutrition for id 1
nutrition = fdc.nutrients(apikey,fdc_id = id)

pd.set_option("display.max_rows", 500,"display.max_columns", 500)

nutrition

                                    Quantity Units
Fatty acids, total saturated           13.33     g
Fatty acids, total monounsaturated     66.67     g
Fatty acids, total trans                0.00     g
Carbohydrate, by difference             0.00     g
Total lipid (fat)                      93.33     g
Sodium, Na                              0.00    mg
Energy                                800.00  kcal
Cholesterol                             0.00    mg
Fatty acids, total polyunsaturated     10.00     g
Protein                                 0.00     g

In [18]:
id = id2
nutrition = fdc.nutrients(apikey,fdc_id = id)

pd.set_option("display.max_rows", 500,"display.max_columns", 500)

nutrition

                                    Quantity Units
Proximates                             0.000     g
Water                                 64.030     g
Energy                               146.000  kcal
Protein                                8.190     g
Total lipid (fat)                      3.240     g
Carbohydrates                          0.000     g
Carbohydrate, by difference           22.450     g
Fiber, total dietary                   7.300     g
Sugars, total including NLEA           4.310     g
Minerals                               0.000    mg
Calcium, Ca                           58.000    mg
Iron, Fe                               2.050    mg
Magnesium, Mg                         45.000    mg
Phosphorus, P                        133.000    mg
Potassium, K                         240.000    mg
Sodium, Na                           327.000    mg
Zinc, Zn                               1.150    mg
Copper, Cu                             0.255    mg
Selenium, Se                           3.300    Âµg
Vitamins and Other Components          0.000     g
Vitamin C, total ascorbic acid         0.200    mg
Thiamin                                0.051    mg
Riboflavin                             0.024    mg
Niacin                                 0.205    mg
Vitamin B-6                            0.748    mg
Folate, total                         40.000    Âµg
Folic acid                             0.000    Âµg
Folate, food                          40.000    Âµg
Folate, DFE                           40.000    Âµg
Choline, total                        38.400    mg
Vitamin B-12                           0.000    Âµg
Vitamin B-12, added                    0.000    Âµg
Vitamin A, RAE                         2.000    Âµg
Retinol                                0.000    Âµg
Carotene, beta                        15.000    Âµg
Carotene, alpha                        0.000    Âµg
Cryptoxanthin, beta                    0.000    Âµg
Lycopene                               0.000    Âµg
Lutein + zeaxanthin                    0.000    Âµg
Vitamin E (alpha-tocopherol)           0.320    mg
Vitamin E, added                       0.000    mg
Vitamin D (D2 + D3)                    0.000    Âµg
Vitamin K (phylloquinone)              3.700    Âµg
Lipids                                 0.000     g
Fatty acids, total saturated           0.339     g
SFA 4:0                                0.000     g
SFA 6:0                                0.000     g
SFA 8:0                                0.000     g
SFA 10:0                               0.000     g
SFA 12:0                               0.000     g
SFA 14:0                               0.005     g
SFA 16:0                               0.273     g
SFA 18:0                               0.047     g
Fatty acids, total monounsaturated     0.739     g
MUFA 16:1                              0.005     g
MUFA 18:1                              0.734     g
MUFA 20:1                              0.000     g
MUFA 22:1                              0.000     g
Fatty acids, total polyunsaturated     1.466     g
PUFA 18:2                              1.413     g
PUFA 18:3                              0.055     g
PUFA 18:4                              0.000     g
PUFA 20:4                              0.000     g
PUFA 2:5 n-3 (EPA)                     0.000     g
PUFA 22:5 n-3 (DPA)                    0.000     g
PUFA 22:6 n-3 (DHA)                    0.000     g
Cholesterol                            0.000    mg
Amino acids                            0.000     g
Alcohol, ethyl                         0.000     g
Caffeine                               0.000    mg
Theobromine                            0.000    mg

We created three spreadsheets for price data on our food items from locations accessible to our populations of interest: Berkeley and Fresno in California and a small province in Greece. 

We first import our spreadsheet and create a dataframe from Berkeley Bowl for our Berkeley population of interest.

In [19]:
#Reads in .csv file (Mediterranean Diet Cost Sheet - Berkeley Bowl.csv file needs to be uploaded to data folder before cell can run)
BerkBowl = pd.read_csv('./Data/Mediterranean Diet Cost Sheet - Berkeley Bowl.csv',index_col=0)
dtype={'Price':float,'Quantity':float, 'FDC':int}

BerkBowl.reset_index(inplace=True)
BerkBowl.head()
BerkBowl.drop(columns=["Food Type"])
BerkBowl.set_index("Food", inplace = True)
BerkBowl

,Food Type,Quantity,Units,Price (pretax),Price per gram,Date,Location,FDCID,Description?
Food,,,,,,,,,
Whole Wheat Bread,Whole Grain,25.0,oz,8.29,0.011690,2/27/22,Berkeley Bowl,1100740,1 loaf
Rice,Whole Grain,32.0,oz,8.79,0.009138,2/27/22,Berkeley Bowl,2077766,1 Bag = 2lbs
Sweet potatoes,Vegetable,4.0,lbs,8.76,0.004828,2/27/22,Berkeley Bowl,1103249,"sweet potato, boiled, made with oil"
Spinach,Vegetable,10.0,oz,2.39,0.008430,2/27/22,Berkeley Bowl,1103136,Raw(1 bag)
Broccoli,Vegetable,1.5,lbs,3.28,0.004821,2/27/22,Berkeley Bowl,1103177,cooked with oil
Tomato,Fruit,1.0,lbs,4.39,0.009678,2/27/22,Berkeley Bowl,1103278,"tomatoes, fresh, cooked"
Avocado,Fruit,6.0,oz,2.19,0.012882,2/27/22,Berkeley Bowl,1102652,raw
Oranges,Fruit,2.0,lbs,4.18,0.004609,2/27/22,Berkeley Bowl,1102597,raw
Greek yogurt,Milk/Dairy,32.0,oz,7.69,0.008479,2/27/22,Berkeley Bowl,170903,"yogurt, greek, plain, lowfat"
Feta,Milk/Dairy,6.0,oz,4.99,0.029353,2/27/22,Berkeley Bowl,173420,NaN
Milk,Milk/Dairy,128.0,oz,6.59,0.001816,2/27/22,Berkeley Bowl,1904187,NaN
Canned tuna,Seafood,12.0,oz,4.39,0.012912,2/27/22,Berkeley Bowl,334194,NaN
Eggs,Eggs,21.0,oz,4.09,0.006874,2/27/22,Berkeley Bowl,747997,NaN
Chickpeas,Fat/oils/nuts,15.5,oz,1.89,0.004305,2/27/22,Berkeley Bowl,1100433,canned
Olive oil,Fat/oils/nuts,25.4,oz,15.39,0.021375,2/27/22,Berkeley Bowl,1582039,NaN

Next, we are just checking the function that converts our data units into hectograms.

In [20]:
print(fdc.units(5,'lbs')) #FDC Units hectograms
print(fdc.units(10,'oz'))

22.679618500000004 hectogram
2.8349523125000005 hectogram

Now we complete the conversion for our Berkeley Bowl data into price/hectograms.

In [21]:
#Conversion code for Berkeley Bowl quantities to hectograms
BerkBowl['FDC Quantity'] = BerkBowl[['Quantity','Units']].T.apply(lambda x : fdc.units(x['Quantity'],x['Units']))

BerkBowl['FDC Price'] = BerkBowl['Price (pretax)']/BerkBowl['FDC Quantity']

BerkBowl.dropna(how='any') 

BerkBowlPrices = BerkBowl.groupby('Food')['FDC Price'].min()

BerkBowlPrices

/opt/conda/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1990: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  result[:] = values

Food
Avocado                1.287499611159685 / hectogram
Broccoli              0.4820774799775989 / hectogram
Canned tuna           1.2904391079888167 / hectogram
Chickpeas             0.4301147618368192 / hectogram
Eggs                  0.6870024017799231 / hectogram
Feta                  2.9336178354734375 / hectogram
Greek yogurt          0.8476773981008542 / hectogram
Milk                  0.1816057884747929 / hectogram
Olive oil              2.137268796866309 / hectogram
Oranges              0.46076612796639405 / hectogram
Rice                  0.9689316423025367 / hectogram
Spinach               0.8430476905949718 / hectogram
Sweet potatoes       0.48281235418488183 / hectogram
Tomato                0.9678293309916124 / hectogram
Whole Wheat Bread     1.1696845782480862 / hectogram
Name: FDC Price, dtype: object

We complete the same process for our next dataframe is from the Stockton Walmart for our Fresno location.

In [22]:
#Creates data frame for Walmart quantities from excel sheet/.csv) (Mediterranean Diet Cost Sheet - Rural Walmart.csv file needs to be uploaded to data folder before cell can run)

WalmartData = pd.read_csv('./Data/Mediterranean Diet Cost Sheet - Rural Walmart.csv',index_col=0)
dtype={'Price':float,'Quantity':float, 'FDC':int}

WalmartData

,Food,Quantity,Units,Highest Price (Pretax),Lowest P (Pretax),Price Per Gram / Litre,Price per hectograms,Date,FDCID,Description?
Food Type,,,,,,,,,,
Whole Grain,Whole Wheat Bread,27.000,oz,18.99,4.78,0.006245,0.000000,2/27/22,1100740,NaN
Whole Grain,Rice,16.000,oz,7.18,0.78,0.001720,0.000017,2/27/22,2077766,NaN
Vegetable,Sweet potatoes,1.500,Ibs,2.94,2.94,0.004324,0.000043,2/27/22,1103249,"sweet potato, boiled, made with oil"
Vegetable,Spinach,16.000,oz,4.98,1.92,0.004238,0.000042,2/27/22,1103136,raw
Vegetable,Broccoli,12.000,oz,2.78,1.00,0.002939,0.000029,2/27/22,1103177,cooked with oil
Fruit,Tomato,16.000,oz,2.98,1.50,0.003311,0.000033,2/27/22,1103278,"tomatoes, fresh, cooked"
Fruit,Avocado,6.000,oz,2.48,0.88,0.005176,0.000052,2/27/22,1102652,raw
Fruit,Oranges,3.000,lbs,4.93,3.89,0.002860,0.000029,2/27/22,1102597,raw
Milk/Dairy,Greek yogurt,5.300,oz,1.24,0.64,0.004260,0.000043,2/27/22,170903,"yogurt, greek, plain, lowfat"
Milk/Dairy,Feta,5.000,oz,3.98,2.54,0.017919,0.000179,2/27/22,173420,NaN
Milk/Dairy,Milk,68.766,oz,5.47,2.22,0.001173,0.000012,2/27/22,1904187,NaN
Seafood,Canned tuna,5.000,Ibs,2.28,0.72,0.005143,0.000051,2/27/22,334194,NaN
Eggs,Eggs,20.500,oz,8.11,0.21,0.003818,0.000038,2/27/22,747997,NaN
Fat/oils/nuts,Chickpeas,15.000,oz,2.30,0.94,0.002211,0.000022,2/27/22,1100433,canned
Fat/oils/nuts,Olive oil,24.419,oz,15.94,4.13,0.005477,0.000055,2/27/22,1582039,NaN

In [23]:
print(fdc.units(1,'lbs'))
print(fdc.units(1,'oz'))
print(fdc.units(1,'grams'))

4.535923700000001 hectogram
0.28349523125000003 hectogram
0.01 hectogram

In [24]:
#Conversion code from quanitity/units to hectorgrams
WalmartData['FDC Quantity'] = WalmartData[['Quantity','Units']].T.apply(lambda x : fdc.units(x['Quantity'],x['Units']))

WalmartData['FDC Price'] = WalmartData['Lowest P (Pretax)']/WalmartData['FDC Quantity']

WalmartData.dropna(how = 'any') 

WalmartPrices = WalmartData.groupby('Food')['FDC Price'].min()

WalmartPrices

/opt/conda/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1990: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  result[:] = values

Food
Avocado               0.5173514419271794 / hectogram
Broccoli              0.2939496829131701 / hectogram
Canned tuna                         nan / milliliter
Chickpeas            0.22105016155070387 / hectogram
Eggs                 0.03613430248493603 / hectogram
Feta                  1.7919172670386847 / hectogram
Greek yogurt          0.4259497292024805 / hectogram
Milk                 0.11387632773182751 / hectogram
Olive oil             0.5965906173543842 / hectogram
Oranges               0.2858660666330579 / hectogram
Rice                  0.1719605645042045 / hectogram
Spinach               0.4232875433949649 / hectogram
Sweet potatoes                      nan / milliliter
Tomato               0.33069339327731634 / hectogram
Whole Wheat Bread     0.6244797708110902 / hectogram
Name: FDC Price, dtype: object

Our last spreadsheet is from an online market accessible to locations in Greece. We will complete the process of creating a dataframe and converting to price/hectogram as done previously.

In [38]:
#Creates International Mediterranean country data from from final excel sheet/.csv)(Mediterranean Diet Cost Sheet - International Mediterranean.csv file needs to be uploaded to data folder before cell can run)
)
InterMed = pd.read_csv('./Data/Mediterranean Diet Cost Sheet - International Mediterranean.csv',index_col=0)
dtype={'Price':float,'Quantity':float, 'FDC':int}

InterMed

,Food,Quantity,Units,Price Per Kg,Price (pretax) U.S,Price per gram,Price per hectograms,Date,Location,FDCID,Description?
FDCID,,,,,,,,,,,
1100740,Whole Wheat Bread,720.00,grams,"â‚¬3,11 EUR / kg",2.51,"0,00311 ($0.0035 USD)",0.3461,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1100740,Whole Wheat (used Google Translate) 1 bag
2116789,Rice,32.30,grams,"â‚¬5,76/ Kg",3.23,"0,00576 (0.0065 USD)",9.9690,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",2077766,Wild Rice
1103249,Sweet potatoes,3.00,kilograms,"â‚¬1,16 EUR / kg",3.90,"0,00116 ($0.0013 USD)",1.1300,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1103249,The market only had regular potatoes (sweet po...
1103136,Spinach,29.15,grams,"â‚¬3,96 EUR / kg",2.00,"0,00396 ($0.0044 USD)",6.8588,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1103136,raw 1 bag
1103177,Broccoli,38.87,grams,"â‚¬4,48 EUR / kg",3.02,"0,00448 ($0.00502 USD)",7.7670,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1103177,cooked with oil 1 stalk
1103278,Tomato,1.00,kilograms,"â‚¬2,42 EUR / kg",2.69,"0,00242 ($0.00271 USD)",0.2690,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1103278,"Organic Greek Tomatoes (tomatoes, fresh, cooked)"
1102652,Avocado,27.86,grams,"â‚¬4,98 EUR / kg",2.40,"0,00498 ($0.00558 USD)",8.6130,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1102652,raw
1102597,Oranges,2.00,kilograms,"â‚¬1,59 EUR / kg",3.43,",00159 ($0.00178 USD)",0.1715,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1102597,raw
170903,Greek yogurt,38.87,grams,"â‚¬5,50 EUR / kg",2.56,"0,00550 ($0.00616 USD)",6.5840,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",170903,"Strained yogurt 2% (yogurt, greek, plain, lowfat)"
173420,Feta,25.91,grams,"â‚¬12,25 EUR / kg",5.45,"0,01225 ($0.014 USD)",21.0260,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",173420,NaN
1904187,Milk,2.00,liters,"â‚¬0,81 EUR (1 Litre)",1.80,"0,00081 ($0.00091 USD)",0.0900,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1904187,NaN
334194,Canned tuna,7.77,grams,"â‚¬54,92 EUR / kg",7.33,"0,06492 ($0.073 USD)",94.2600,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",334194,White Tuna in Olive Oil
747997,Eggs,307.00,oz,"â‚¬0,25 per egg",4.14,"0,25 per egg ($0.28 USD)",0.0475,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",747997,NaN
1100433,Chickpeas,32.30,grams,"â‚¬5,70 EUR / kg",3.17,"0,00570 ($0.0064 USD)",94.2600,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1100433,(Peeled Chickpeas Imported)
1582039,Olive oil,1.00,liter,"â‚¬8,89 EUR (1 Litre)",9.89,"0,0089 ($0.0100 USD)",0.9890,26/02/2022,"Alfa-Beta Vassilopoulos, Online Shop",1582039,1 Litre

In [39]:
print(fdc.units(1,'lbs'))
print(fdc.units(1,'oz'))
print(fdc.units(1,'gram'))
print(fdc.units(1,'grain'))
print(fdc.units(1,'kilogram'))
print(fdc.units(1,'liter'))

4.535923700000001 hectogram
0.28349523125000003 hectogram
0.01 hectogram
0.0006479891 hectogram
10.0 hectogram
10.0 deciliter

In [40]:
#Conversion
InterMed['FDC Quantity'] = InterMed[['Quantity','Units']].T.apply(lambda x : fdc.units(x['Quantity'],x['Units']))

InterMed['FDC Price'] = InterMed['Price (pretax) U.S']/InterMed['FDC Quantity']

InterMed.dropna(how = 'any') 

PricesInterMed = InterMed.groupby('Food')['FDC Price'].min()

PricesInterMed

/opt/conda/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1990: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  result[:] = values

Food
Avocado               8.614501076812633 / hectogram
Broccoli              7.769488037046566 / hectogram
Canned tuna           94.33719433719435 / hectogram
Chickpeas             9.814241486068113 / hectogram
Eggs                 0.0475681441274472 / hectogram
Feta                 21.034349671941335 / hectogram
Greek yogurt          6.586056084383844 / hectogram
Milk                               0.09 / deciliter
Olive oil            0.9890000000000001 / deciliter
Oranges                          0.1715 / hectogram
Rice                 10.000000000000002 / hectogram
Spinach                6.86106346483705 / hectogram
Sweet potatoes                     0.13 / hectogram
Tomato                            0.269 / hectogram
Whole Wheat Bread    0.3486111111111111 / hectogram
Name: FDC Price, dtype: object

In [28]:
#Prints bmin and bmax requirements
bminM48 = get_dri_min(5, 'M')
bmaxM48= get_dri_max(5, 'M')
bminM48

Nutrition
Energy                            1400.0
Protein                             19.0
Fiber, total dietary                19.6
Folate, DFE                        200.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            10.0
Magnesium, Mg                      130.0
Niacin                               8.0
Phosphorus, P                      500.0
Potassium, K                      3800.0
Riboflavin                           0.6
Thiamin                              0.6
Vitamin A, RAE                     400.0
Vitamin B-12                         1.2
Vitamin B-6                          0.6
Vitamin C, total ascorbic acid      25.0
Vitamin E (alpha-tocopherol)         7.0
Vitamin K (phylloquinone)           55.0
Zinc, Zn                             5.0
Name: M 4-8, dtype: float64

In [29]:
bmaxM48

Nutrition
Sodium, Na    1900
Name: M 4-8, dtype: int64

### Deliverable [A] Solution

#### What is the minimum cost diet for the population you're concerned with? How much does it cost, and of what does it consist? How does it vary with age, sex, and level of activity?

We now begin the final assessment for solving the subsistence food problem to determine what a minimum cost mediterranean diet looks like in our given populations of interest. 

We begin with Berkeley Bowl for the Berkeley population.

In [30]:
#Final matrix code for minumium price for diet for Berkeley Bowl 
from  scipy.optimize import linprog as lp
import numpy as np
import warnings

def solve_subsistence_problem(FoodNutrients,Prices,diet_min,diet_max,max_weight=None,tol=1e-6):
    
    p = Prices.apply(lambda x:x.magnitude).dropna()

    # Compile list that we have both prices and nutritional info for; drop if either missing
    use = p.index.intersection(FoodNutrients.columns)
    p = p[use]

    # Drop nutritional information for foods we don't know the price of,
    # and replace missing nutrients with zeros.
    Aall = FoodNutrients[p.index].fillna(0)

    # Drop rows of A that we don't have constraints for.
    Amin = Aall.loc[Aall.index.intersection(diet_min.index)]

    Amax = Aall.loc[Aall.index.intersection(diet_max.index)]

    # Minimum requirements involve multiplying constraint by -1 to make <=.
    A = pd.concat([Amin,
                   -Amax])

    b = pd.concat([diet_min,
                   -diet_max]) # Note sign change for max constraints

    # Make sure order of p, A, b are consistent
    A = A.reindex(p.index,axis=1)
    A = A.reindex(b.index,axis=0)

    if max_weight is not None:
        # Add up weights of foods consumed
        A.loc['Hectograms'] = -1
        b.loc['Hectograms'] = -max_weight
        
    # Now we solve the problem.

    result = lp(p, -A, -b, method='interior-point')

    result.A = A
    result.b = b
    
    if result.success:
        result.diet = pd.Series(result.x,index=p.index)
    else: # No feasible solution?
        warnings.warn(result.message)
        result.diet = pd.Series(result.x,index=p.index)*np.nan 
        

    return result
Pricesbb = BerkBowlPrices
dietM4to8=solve_subsistence_problem(FoodNutrients,Pricesbb,bminM48,bmaxM48,max_weight=None,tol=1e-6)
dietM4to8

       A:                                 Avocado  Broccoli  Canned tuna  Chickpeas  \
Nutrition
Energy                          160.000    61.000      376.000    146.000
Protein                           2.000     2.840       19.000      8.190
Fiber, total dietary              6.700     2.600        0.000      7.300
Folate, DFE                      81.000    54.000        0.000     40.000
Calcium, Ca                      12.000    48.000       18.000     58.000
Carbohydrate, by difference       8.530     6.700        0.080     22.450
Iron, Fe                          0.550     0.740        1.670      2.050
Magnesium, Mg                    29.000    21.000       22.700     45.000
Niacin                            1.738     0.612        9.920      0.205
Phosphorus, P                    52.000    67.000      137.000    133.000
Potassium, K                    485.000   319.000      176.000    240.000
Riboflavin                        0.130     0.112        0.082      0.024
Thiamin                           0.067     0.064        0.030      0.051
Vitamin A, RAE                    7.000    30.000        0.000      2.000
Vitamin B-12                      0.000     0.000        2.570      0.000
Vitamin B-6                       0.257     0.159        0.320      0.748
Vitamin C, total ascorbic acid   10.000    76.500        0.000      0.200
Vitamin E (alpha-tocopherol)      2.070     1.140        0.000      0.320
Vitamin K (phylloquinone)        21.000   106.000        0.000      3.700
Zinc, Zn                          0.640     0.410        0.660      1.150
Sodium, Na                       -7.000  -150.000     -219.000   -327.000

                                   Eggs      Feta  Greek yogurt    Milk  \
Nutrition
Energy                          231.000  1107.000       305.000   62.00
Protein                          10.700    14.210         9.950    3.33
Fiber, total dietary              0.000     0.000         0.000    0.00
Folate, DFE                       0.000    32.000        12.000    0.00
Calcium, Ca                       0.000   493.000       115.000  125.00
Carbohydrate, by difference       2.360     3.880         3.940    5.00
Iron, Fe                          0.000     0.650         0.040    0.04
Magnesium, Mg                     0.000    19.000        11.000    0.00
Niacin                            0.000     0.991         0.197    0.00
Phosphorus, P                     0.000   337.000       137.000    0.00
Potassium, K                      0.000    62.000       141.000  167.00
Riboflavin                        0.391     0.844         0.233    0.00
Thiamin                           0.000     0.154         0.044    0.00
Vitamin A, RAE                    0.000   125.000        90.000    0.00
Vitamin B-12                      0.000     1.690         0.520    0.00
Vitamin B-6                       0.000     0.424         0.055    0.00
Vitamin C, total ascorbic acid    0.000     0.000         0.800    0.00
Vitamin E (alpha-tocopherol)      0.000     0.180         0.040    0.00
Vitamin K (phylloquinone)         0.000     1.800         0.200    0.00
Zinc, Zn                          0.000     2.880         0.600    0.00
Sodium, Na                       -0.000 -1139.000       -34.000  -52.00

                                Olive oil  Oranges     Rice  Spinach  \
Nutrition
Energy                              800.0   47.000  356.000   23.000
Protein                               0.0    0.940    6.670    2.860
Fiber, total dietary                  0.0    2.400    0.000    2.200
Folate, DFE                           0.0   30.000    0.000  194.000
Calcium, Ca                           0.0   40.000    0.000   99.000
Carbohydrate, by difference           0.0   11.750   77.780    3.630
Iron, Fe                              0.0    0.100    3.200    2.710
Magnesium, Mg                         0.0   10.000    0.000   79.000
Niacin                                0.0    0.282    3.556    0.724
Phosphorus, P                         0.0   14.000    0.000   49.000
Potassium, K                          0.0  181.000   89.000  558.000
Riboflavin                            0.0    0.040    0.000    0.189
Thiamin                               0.0    0.087    0.000    0.078
Vitamin A, RAE                        0.0   11.000    0.000  469.000
Vitamin B-12                          0.0    0.000    0.000    0.000
Vitamin B-6                           0.0    0.060    0.000    0.195
Vitamin C, total ascorbic acid        0.0   53.200    0.000   28.100
Vitamin E (alpha-tocopherol)          0.0    0.180    0.000    2.030
Vitamin K (phylloquinone)             0.0    0.000    0.000  482.900
Zinc, Zn                              0.0    0.070    0.000    0.530
Sodium, Na                           -0.0   -0.000   -0.000  -79.000

                                Sweet potatoes  Whole Wheat Bread
Nutrition
Energy                                 114.000            254.000
Protein                                  1.300             12.300
Fiber, total dietary                     2.400              6.000
Folate, DFE                              6.000             42.000
Calcium, Ca                             26.000            163.000
Carbohydrate, by difference             16.810             43.100
Iron, Fe                                 0.690              2.560
Magnesium, Mg                           17.000             77.000
Niacin                                   0.510              4.430
Phosphorus, P                           30.000            212.000
Potassium, K                           218.000            250.000
Riboflavin                               0.045              0.166
Thiamin                                  0.053              0.391
Vitamin A, RAE                         747.000              0.000
Vitamin B-12                             0.000              0.000
Vitamin B-6                              0.157              0.216
Vitamin C, total ascorbic acid          12.100              0.000
Vitamin E (alpha-tocopherol)             1.450              0.540
Vitamin K (phylloquinone)                7.600              7.800
Zinc, Zn                                 0.190              1.760
Sodium, Na                            -173.000           -450.000
       b: Nutrition
Energy                            1400.0
Protein                             19.0
Fiber, total dietary                19.6
Folate, DFE                        200.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            10.0
Magnesium, Mg                      130.0
Niacin                               8.0
Phosphorus, P                      500.0
Potassium, K                      3800.0
Riboflavin                           0.6
Thiamin                              0.6
Vitamin A, RAE                     400.0
Vitamin B-12                         1.2
Vitamin B-6                          0.6
Vitamin C, total ascorbic acid      25.0
Vitamin E (alpha-tocopherol)         7.0
Vitamin K (phylloquinone)           55.0
Zinc, Zn                             5.0
Sodium, Na                       -1900.0
Name: M 4-8, dtype: float64
     con: array([], dtype=float64)
    diet: Avocado              1.390481e-10
Broccoli             4.029166e+00
Canned tuna          4.003637e-01
Chickpeas            1.430445e+00
Eggs                 1.203777e-10
Feta                 1.757179e-11
Greek yogurt         3.289716e-01
Milk                 8.820315e+00
Olive oil            4.292125e-11
Oranges              1.034902e-09
Rice                 3.658811e-02
Spinach              8.326948e-01
Sweet potatoes       7.792780e-11
Whole Wheat Bread    4.545903e-01
dtype: float64
     fun: 6.224132886228146
 message: 'Optimization terminated successfully.'
     nit: 16
   slack: array([2.16127773e-08, 5.26270127e+01, 5.87755033e+00, 2.59376016e+02,
       5.80478411e+02, 4.30105729e-09, 4.86009899e-01, 1.32475797e+02,
       1.54231986e+00, 1.97297444e+02, 4.88162186e-08, 2.27918826e-01,
       3.69080322e-11, 1.43877177e+02, 1.43317358e-10, 1.51738702e+00,
       3.07179214e+02, 7.34021732e-10, 7.83104183e+02, 1.54515511e-10,
       2.75756520e-08])
  status: 0
 success: True
       x: array([1.39048100e-10, 4.02916633e+00, 4.00363715e-01, 1.43044487e+00,
       1.20377668e-10, 1.75717935e-11, 3.28971640e-01, 8.82031469e+00,
       4.29212500e-11, 1.03490171e-09, 3.65881100e-02, 8.32694776e-01,
       7.79277967e-11, 4.54590308e-01])

A minimum cost mediterranean diet in Berkeley using Berkely Bowl as the market is $6.22.

We repeat the same for the Stockton Walmart for our Fresno population.

In [31]:
#Final matrix code for minumium price for diet for Walmart 
from  scipy.optimize import linprog as lp
import numpy as np
import warnings

def solve_subsistence_problem(FoodNutrients,Prices,diet_min,diet_max,max_weight=None,tol=1e-6):
    
    p = Prices.apply(lambda x:x.magnitude).dropna()

    # Compile list that we have both prices and nutritional info for; drop if either missing
    use = p.index.intersection(FoodNutrients.columns)
    p = p[use]

    # Drop nutritional information for foods we don't know the price of,
    # and replace missing nutrients with zeros.
    Aall = FoodNutrients[p.index].fillna(0)

    # Drop rows of A that we don't have constraints for.
    Amin = Aall.loc[Aall.index.intersection(diet_min.index)]

    Amax = Aall.loc[Aall.index.intersection(diet_max.index)]

    # Minimum requirements involve multiplying constraint by -1 to make <=.
    A = pd.concat([Amin,
                   -Amax])

    b = pd.concat([diet_min,
                   -diet_max]) # Note sign change for max constraints

    # Make sure order of p, A, b are consistent
    A = A.reindex(p.index,axis=1)
    A = A.reindex(b.index,axis=0)

    if max_weight is not None:
        # Add up weights of foods consumed
        A.loc['Hectograms'] = -1
        b.loc['Hectograms'] = -max_weight
        
    # Now solve problem!  (Note that the linear program solver we'll use assumes
    # "less-than-or-equal" constraints.  We can switch back and forth by
    # multiplying $A$ and $b$ by $-1$.)

    result = lp(p, -A, -b, method='interior-point')

    result.A = A
    result.b = b
    
    if result.success:
        result.diet = pd.Series(result.x,index=p.index)
    else: # No feasible solution?
        warnings.warn(result.message)
        result.diet = pd.Series(result.x,index=p.index)*np.nan 
        

    return result
PricesW = WalmartPrices
dietM4to8=solve_subsistence_problem(FoodNutrients,PricesW,bminM48,bmaxM48,max_weight=None,tol=1e-6)
dietM4to8

       A:                                 Avocado  Broccoli  Chickpeas     Eggs  \
Nutrition
Energy                          160.000    61.000    146.000  231.000
Protein                           2.000     2.840      8.190   10.700
Fiber, total dietary              6.700     2.600      7.300    0.000
Folate, DFE                      81.000    54.000     40.000    0.000
Calcium, Ca                      12.000    48.000     58.000    0.000
Carbohydrate, by difference       8.530     6.700     22.450    2.360
Iron, Fe                          0.550     0.740      2.050    0.000
Magnesium, Mg                    29.000    21.000     45.000    0.000
Niacin                            1.738     0.612      0.205    0.000
Phosphorus, P                    52.000    67.000    133.000    0.000
Potassium, K                    485.000   319.000    240.000    0.000
Riboflavin                        0.130     0.112      0.024    0.391
Thiamin                           0.067     0.064      0.051    0.000
Vitamin A, RAE                    7.000    30.000      2.000    0.000
Vitamin B-12                      0.000     0.000      0.000    0.000
Vitamin B-6                       0.257     0.159      0.748    0.000
Vitamin C, total ascorbic acid   10.000    76.500      0.200    0.000
Vitamin E (alpha-tocopherol)      2.070     1.140      0.320    0.000
Vitamin K (phylloquinone)        21.000   106.000      3.700    0.000
Zinc, Zn                          0.640     0.410      1.150    0.000
Sodium, Na                       -7.000  -150.000   -327.000   -0.000

                                    Feta  Greek yogurt    Milk  Olive oil  \
Nutrition
Energy                          1107.000       305.000   62.00      800.0
Protein                           14.210         9.950    3.33        0.0
Fiber, total dietary               0.000         0.000    0.00        0.0
Folate, DFE                       32.000        12.000    0.00        0.0
Calcium, Ca                      493.000       115.000  125.00        0.0
Carbohydrate, by difference        3.880         3.940    5.00        0.0
Iron, Fe                           0.650         0.040    0.04        0.0
Magnesium, Mg                     19.000        11.000    0.00        0.0
Niacin                             0.991         0.197    0.00        0.0
Phosphorus, P                    337.000       137.000    0.00        0.0
Potassium, K                      62.000       141.000  167.00        0.0
Riboflavin                         0.844         0.233    0.00        0.0
Thiamin                            0.154         0.044    0.00        0.0
Vitamin A, RAE                   125.000        90.000    0.00        0.0
Vitamin B-12                       1.690         0.520    0.00        0.0
Vitamin B-6                        0.424         0.055    0.00        0.0
Vitamin C, total ascorbic acid     0.000         0.800    0.00        0.0
Vitamin E (alpha-tocopherol)       0.180         0.040    0.00        0.0
Vitamin K (phylloquinone)          1.800         0.200    0.00        0.0
Zinc, Zn                           2.880         0.600    0.00        0.0
Sodium, Na                     -1139.000       -34.000  -52.00       -0.0

                                Oranges     Rice  Spinach  Whole Wheat Bread
Nutrition
Energy                           47.000  356.000   23.000            254.000
Protein                           0.940    6.670    2.860             12.300
Fiber, total dietary              2.400    0.000    2.200              6.000
Folate, DFE                      30.000    0.000  194.000             42.000
Calcium, Ca                      40.000    0.000   99.000            163.000
Carbohydrate, by difference      11.750   77.780    3.630             43.100
Iron, Fe                          0.100    3.200    2.710              2.560
Magnesium, Mg                    10.000    0.000   79.000             77.000
Niacin                            0.282    3.556    0.724              4.430
Phosphorus, P                    14.000    0.000   49.000            212.000
Potassium, K                    181.000   89.000  558.000            250.000
Riboflavin                        0.040    0.000    0.189              0.166
Thiamin                           0.087    0.000    0.078              0.391
Vitamin A, RAE                   11.000    0.000  469.000              0.000
Vitamin B-12                      0.000    0.000    0.000              0.000
Vitamin B-6                       0.060    0.000    0.195              0.216
Vitamin C, total ascorbic acid   53.200    0.000   28.100              0.000
Vitamin E (alpha-tocopherol)      0.180    0.000    2.030              0.540
Vitamin K (phylloquinone)         0.000    0.000  482.900              7.800
Zinc, Zn                          0.070    0.000    0.530              1.760
Sodium, Na                       -0.000   -0.000  -79.000           -450.000
       b: Nutrition
Energy                            1400.0
Protein                             19.0
Fiber, total dietary                19.6
Folate, DFE                        200.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            10.0
Magnesium, Mg                      130.0
Niacin                               8.0
Phosphorus, P                      500.0
Potassium, K                      3800.0
Riboflavin                           0.6
Thiamin                              0.6
Vitamin A, RAE                     400.0
Vitamin B-12                         1.2
Vitamin B-6                          0.6
Vitamin C, total ascorbic acid      25.0
Vitamin E (alpha-tocopherol)         7.0
Vitamin K (phylloquinone)           55.0
Zinc, Zn                             5.0
Sodium, Na                       -1900.0
Name: M 4-8, dtype: float64
     con: array([], dtype=float64)
    diet: Avocado              3.977260e-07
Broccoli             1.828846e-06
Chickpeas            1.061463e+00
Eggs                 6.861040e-02
Feta                 6.918091e-08
Greek yogurt         2.307692e+00
Milk                 1.104886e+00
Olive oil            8.667215e-08
Oranges              4.799763e-07
Rice                 8.812763e-01
Spinach              5.260127e+00
Whole Wheat Bread    8.705071e-02
dtype: float64
     fun: 3.778350772303662
 message: 'Optimization terminated successfully.'
     nit: 17
   slack: array([2.69480454e-04, 3.90611346e+01, 2.43276117e-01, 8.94271834e+02,
       2.30553883e-03, 3.54048794e-04, 9.61038403e+00, 3.65403493e+02,
       2.77314446e-06, 2.33529639e+02, 6.96198749e-05, 9.98608908e-01,
       5.20459847e-08, 2.27681504e+03, 8.58844913e-08, 1.36542597e+00,
       1.24868195e+02, 4.15704497e+00, 2.49018366e+03, 5.46376290e-01,
       9.62262593e+02])
  status: 0
 success: True
       x: array([3.97726010e-07, 1.82884559e-06, 1.06146343e+00, 6.86103962e-02,
       6.91809138e-08, 2.30769225e+00, 1.10488637e+00, 8.66721501e-08,
       4.79976340e-07, 8.81276302e-01, 5.26012738e+00, 8.70507057e-02])

A minimum cost mediterranean diet for our Fresno population using Walmart as their market is $3.78.

We complete the assessment by repeating the process for our population in Greece.

In [41]:
#Final matrix code for minumium price for diet for International Mediteranean Country
from  scipy.optimize import linprog as lp
import numpy as np
import warnings

def solve_subsistence_problem(FoodNutrients,Prices,diet_min,diet_max,max_weight=None,tol=1e-6):
   
    p = Prices.apply(lambda x:x.magnitude).dropna()

    # Compile list that we have both prices and nutritional info for; drop if either missing
    use = p.index.intersection(FoodNutrients.columns)
    p = p[use]

    # Drop nutritional information for foods we don't know the price of,
    # and replace missing nutrients with zeros.
    Aall = FoodNutrients[p.index].fillna(0)

    # Drop rows of A that we don't have constraints for.
    Amin = Aall.loc[Aall.index.intersection(diet_min.index)]

    Amax = Aall.loc[Aall.index.intersection(diet_max.index)]

    # Minimum requirements involve multiplying constraint by -1 to make <=.
    A = pd.concat([Amin,
                   -Amax])

    b = pd.concat([diet_min,
                   -diet_max]) # Note sign change for max constraints

    # Make sure order of p, A, b are consistent
    A = A.reindex(p.index,axis=1)
    A = A.reindex(b.index,axis=0)

    if max_weight is not None:
        # Add up weights of foods consumed
        A.loc['Hectograms'] = -1
        b.loc['Hectograms'] = -max_weight
        
    # Now solve problem!  (Note that the linear program solver we'll use assumes
    # "less-than-or-equal" constraints.  We can switch back and forth by
    # multiplying $A$ and $b$ by $-1$.)

    result = lp(p, -A, -b, method='interior-point')

    result.A = A
    result.b = b
    
    if result.success:
        result.diet = pd.Series(result.x,index=p.index)
    else: # No feasible solution?
        warnings.warn(result.message)
        result.diet = pd.Series(result.x,index=p.index)*np.nan 
        

    return result
PricesIM = PricesInterMed
dietM4to8=solve_subsistence_problem(FoodNutrients,PricesIM,bminM48,bmaxM48,max_weight=None,tol=1e-6)
dietM4to8

       A:                                 Avocado  Broccoli  Canned tuna  Chickpeas  \
Nutrition
Energy                          160.000    61.000      376.000    146.000
Protein                           2.000     2.840       19.000      8.190
Fiber, total dietary              6.700     2.600        0.000      7.300
Folate, DFE                      81.000    54.000        0.000     40.000
Calcium, Ca                      12.000    48.000       18.000     58.000
Carbohydrate, by difference       8.530     6.700        0.080     22.450
Iron, Fe                          0.550     0.740        1.670      2.050
Magnesium, Mg                    29.000    21.000       22.700     45.000
Niacin                            1.738     0.612        9.920      0.205
Phosphorus, P                    52.000    67.000      137.000    133.000
Potassium, K                    485.000   319.000      176.000    240.000
Riboflavin                        0.130     0.112        0.082      0.024
Thiamin                           0.067     0.064        0.030      0.051
Vitamin A, RAE                    7.000    30.000        0.000      2.000
Vitamin B-12                      0.000     0.000        2.570      0.000
Vitamin B-6                       0.257     0.159        0.320      0.748
Vitamin C, total ascorbic acid   10.000    76.500        0.000      0.200
Vitamin E (alpha-tocopherol)      2.070     1.140        0.000      0.320
Vitamin K (phylloquinone)        21.000   106.000        0.000      3.700
Zinc, Zn                          0.640     0.410        0.660      1.150
Sodium, Na                       -7.000  -150.000     -219.000   -327.000

                                   Eggs      Feta  Greek yogurt    Milk  \
Nutrition
Energy                          231.000  1107.000       305.000   62.00
Protein                          10.700    14.210         9.950    3.33
Fiber, total dietary              0.000     0.000         0.000    0.00
Folate, DFE                       0.000    32.000        12.000    0.00
Calcium, Ca                       0.000   493.000       115.000  125.00
Carbohydrate, by difference       2.360     3.880         3.940    5.00
Iron, Fe                          0.000     0.650         0.040    0.04
Magnesium, Mg                     0.000    19.000        11.000    0.00
Niacin                            0.000     0.991         0.197    0.00
Phosphorus, P                     0.000   337.000       137.000    0.00
Potassium, K                      0.000    62.000       141.000  167.00
Riboflavin                        0.391     0.844         0.233    0.00
Thiamin                           0.000     0.154         0.044    0.00
Vitamin A, RAE                    0.000   125.000        90.000    0.00
Vitamin B-12                      0.000     1.690         0.520    0.00
Vitamin B-6                       0.000     0.424         0.055    0.00
Vitamin C, total ascorbic acid    0.000     0.000         0.800    0.00
Vitamin E (alpha-tocopherol)      0.000     0.180         0.040    0.00
Vitamin K (phylloquinone)         0.000     1.800         0.200    0.00
Zinc, Zn                          0.000     2.880         0.600    0.00
Sodium, Na                       -0.000 -1139.000       -34.000  -52.00

                                Olive oil  Oranges     Rice  Spinach  \
Nutrition
Energy                              800.0   47.000  356.000   23.000
Protein                               0.0    0.940    6.670    2.860
Fiber, total dietary                  0.0    2.400    0.000    2.200
Folate, DFE                           0.0   30.000    0.000  194.000
Calcium, Ca                           0.0   40.000    0.000   99.000
Carbohydrate, by difference           0.0   11.750   77.780    3.630
Iron, Fe                              0.0    0.100    3.200    2.710
Magnesium, Mg                         0.0   10.000    0.000   79.000
Niacin                                0.0    0.282    3.556    0.724
Phosphorus, P                         0.0   14.000    0.000   49.000
Potassium, K                          0.0  181.000   89.000  558.000
Riboflavin                            0.0    0.040    0.000    0.189
Thiamin                               0.0    0.087    0.000    0.078
Vitamin A, RAE                        0.0   11.000    0.000  469.000
Vitamin B-12                          0.0    0.000    0.000    0.000
Vitamin B-6                           0.0    0.060    0.000    0.195
Vitamin C, total ascorbic acid        0.0   53.200    0.000   28.100
Vitamin E (alpha-tocopherol)          0.0    0.180    0.000    2.030
Vitamin K (phylloquinone)             0.0    0.000    0.000  482.900
Zinc, Zn                              0.0    0.070    0.000    0.530
Sodium, Na                           -0.0   -0.000   -0.000  -79.000

                                Sweet potatoes  Whole Wheat Bread
Nutrition
Energy                                 114.000            254.000
Protein                                  1.300             12.300
Fiber, total dietary                     2.400              6.000
Folate, DFE                              6.000             42.000
Calcium, Ca                             26.000            163.000
Carbohydrate, by difference             16.810             43.100
Iron, Fe                                 0.690              2.560
Magnesium, Mg                           17.000             77.000
Niacin                                   0.510              4.430
Phosphorus, P                           30.000            212.000
Potassium, K                           218.000            250.000
Riboflavin                               0.045              0.166
Thiamin                                  0.053              0.391
Vitamin A, RAE                         747.000              0.000
Vitamin B-12                             0.000              0.000
Vitamin B-6                              0.157              0.216
Vitamin C, total ascorbic acid          12.100              0.000
Vitamin E (alpha-tocopherol)             1.450              0.540
Vitamin K (phylloquinone)                7.600              7.800
Zinc, Zn                                 0.190              1.760
Sodium, Na                            -173.000           -450.000
       b: Nutrition
Energy                            1400.0
Protein                             19.0
Fiber, total dietary                19.6
Folate, DFE                        200.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            10.0
Magnesium, Mg                      130.0
Niacin                               8.0
Phosphorus, P                      500.0
Potassium, K                      3800.0
Riboflavin                           0.6
Thiamin                              0.6
Vitamin A, RAE                     400.0
Vitamin B-12                         1.2
Vitamin B-6                          0.6
Vitamin C, total ascorbic acid      25.0
Vitamin E (alpha-tocopherol)         7.0
Vitamin K (phylloquinone)           55.0
Zinc, Zn                             5.0
Sodium, Na                       -1900.0
Name: M 4-8, dtype: float64
     con: array([], dtype=float64)
    diet: Avocado              6.103401e-09
Broccoli             7.396533e-09
Canned tuna          7.866355e-10
Chickpeas            5.132445e-09
Eggs                 1.003481e-06
Feta                 1.224617e-08
Greek yogurt         2.307692e+00
Milk                 3.401384e-06
Olive oil            4.850282e-08
Oranges              1.022414e+01
Rice                 5.615106e-09
Spinach              1.845065e-08
Sweet potatoes       5.021624e+00
Whole Wheat Bread    2.117327e+00
dtype: float64
     fun: 18.342966407880784
 message: 'Optimization terminated successfully.'
     nit: 18
   slack: array([8.94647408e+02, 4.61434859e+01, 2.96937927e+01, 2.53473936e+02,
       1.50037122e+02, 1.74896255e+02, 9.73737357e-08, 2.46027803e+02,
       7.27861009e+00, 5.58813868e+02, 7.33254524e-05, 9.24107631e-01,
       1.48505947e+00, 3.67131130e+03, 4.52274063e-09, 1.38610907e+00,
       5.81531946e+02, 3.35736470e+00, 1.41045979e-01, 1.78090951e+00,
       1.78068333e-05])
  status: 0
 success: True
       x: array([6.10340091e-09, 7.39653274e-09, 7.86635469e-10, 5.13244481e-09,
       1.00348072e-06, 1.22461652e-08, 2.30769227e+00, 3.40138440e-06,
       4.85028217e-08, 1.02241379e+01, 5.61510553e-09, 1.84506543e-08,
       5.02162446e+00, 2.11732715e+00])

A minimum cost diet for our Greece population using an online Greece-based market is $18.34.